Add ability to check for update
theparanoids/aterm pull request #11
Opened 2020-09-09 17:55 UTC by JoelAtDeluxe

This PR adds the ability to notify the user of new releases. This will not automatically install a new version (nor prevent access for an out-of-date version), but simply alert the user when one is available. 

Note: this is "complete" and ready for review, except that we currently do not track versions for ATerm. A separate PR providing those values needs to be merged first (see PR #9 )

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2020-09-10 20:36 UTC, jkennedyvz reviewed
Hi Joel,

This looks great. I'm holding off on approval until we get the other PRs closed.

2020-09-10 22:52 UTC, jrozner commented
Does this handle untagged versions and what happens when the only version information we have is a hash?

2020-09-11 00:33 UTC, JoelAtDeluxe commented
Regarding untagged versions and hashing:

The short version is that, currently, we can only act on proper semantic tags. 
In a situation where we lack a proper tag (either malformed, or completely missing), the system will default to a semantic version of `0.0.0-development`. In this situation, all updates are ignored, but the system chugs along fine.

2020-09-22 23:05 UTC, jrozner requested changes

2020-09-22 23:05 UTC, jrozner commented on cmd/aterm/climain.go
> +	appdialogs.NotifyUpdate("v30.0.0", "google", "go-github")
Code looks fine. Let's get #8 in and pull this data from the variables exposed by go-info and maybe setup a variable for the org/repo that we can populate from CI to automatically fill it in at build time like we do in the ashirt repo.

2020-09-23 19:25 UTC, closed without merging

2020-09-23 19:26 UTC, JoelAtDeluxe commented
This was based off of js-revised-start, which was squashed into master. This generated a lot of unnecessary conflicts to resolve, so instead migrated it to PR #15 (via git cherry-pick)